In [ ]:
# Mount Google Drive (if using Colab)
try:
    from google.colab import drive
    drive.mount('/content/drive')
    IN_COLAB = True
except:
    IN_COLAB = False
    print("Not running in Colab")

Mounted at /content/drive

# [GPT Link](https://chatgpt.com/share/69b327a6-da94-8005-80c3-f7f09081bc40)

## [Word File](https://docs.google.com/document/d/1ufwWzABa8MhAhmbVzq7El8mLDy3Ra8m-l1jWfWW9ZRE/edit?usp=sharing)

# [Policy_en CSV Link](https://drive.google.com/file/d/17ShQTtD0Ryy6wycrrLfkJ3Ak-80nkp-v/view?usp=sharing)

In [ ]:
import pandas as pd
Policy_Csv = "/content/drive/MyDrive/hf_models/agent_project/Policy_en.csv"
df = pd.read_csv(Policy_Csv)
df

,policy_id,section,policy_name,rule_id,rule_description,threshold_value,condition,approval_required,risk_level
0,1,Financial,Hardware Purchase Policy,1,Purchases up to $1500 are auto-approved,1500.0,amount <= 1500,No,Medium
1,1,Financial,Hardware Purchase Policy,2,Purchases between $1501–$3000 require manager ...,3000.0,1500 < amount <= 3000,Manager,Medium
2,1,Financial,Hardware Purchase Policy,3,"Purchases above $3000 require manager, finance...",3000.0,amount > 3000,Manager+Finance+CTO,Medium
3,1,Financial,Hardware Purchase Policy,4,Annual hardware budget per employee is $2500,2500.0,annual_budget_limit,No,Medium
4,1,Financial,Hardware Purchase Policy,5,Vendor must be selected from approved vendor list,NaN,vendor_approved == true,No,Medium
5,2,Financial,Travel Expense Policy,1,Economy class required for flights under 6 hours,6.0,flight_hours <= 6,No,Medium
6,2,Financial,Travel Expense Policy,2,Business class allowed for flights over 6 hour...,6.0,flight_hours > 6 AND role == executive,Manager,Medium
7,2,Financial,Travel Expense Policy,3,Hotel cost must not exceed $250 regional,250.0,region == regional,No,Medium
8,2,Financial,Travel Expense Policy,4,Hotel cost must not exceed $400 international ...,400.0,region == international,No,Medium
9,2,Financial,Travel Expense Policy,5,Receipts mandatory for reimbursement,NaN,receipt_provided == true,No,Medium
10,3,Security,Software Installation Policy,1,Only software from approved registry allowed,NaN,software_approved == true,IT,High
11,3,Security,Software Installation Policy,2,SaaS handling customer data requires security ...,NaN,handles_customer_data == true,Security+Legal,High
12,3,Security,Software Installation Policy,3,No pirated software allowed,NaN,software_legitimate == true,IT,High
13,4,Security,Data Handling Policy,1,Restricted data must be encrypted at rest,NaN,data_classification == restricted,Security,Critical
14,4,Security,Data Handling Policy,2,Restricted data must not be shared via email,NaN,data_shared_email == false,Security,Critical
15,4,Security,Data Handling Policy,3,External sharing requires legal approval,NaN,external_sharing == true,Legal,Critical
16,5,Legal,Contract Termination Policy,1,Contracts must include minimum 30-day terminat...,30.0,termination_notice_days >= 30,Legal,High
17,5,Legal,Contract Termination Policy,2,Liability cap must not exceed 12 months of con...,12.0,liability_cap_months <= 12,Legal,High
18,5,Legal,Contract Termination Policy,3,Indemnification clauses must be reviewed by legal,NaN,indemnification_clause == true,Legal,High
19,6,Legal,Vendor Agreement Policy,1,Vendor must pass compliance screening,NaN,vendor_screened == true,Compliance,High
20,6,Legal,Vendor Agreement Policy,2,Vendors processing customer data must comply w...,NaN,processes_customer_data == true,Legal,High
21,6,Legal,Vendor Agreement Policy,3,Payment terms must not exceed Net 60 unless CF...,60.0,payment_terms_days <= 60,CFO_if_exceeds,High
22,7,HR,Conflict of Interest Policy,1,Employees must disclose financial interest in ...,NaN,conflict_disclosed == true,HR,High
23,7,HR,Conflict of Interest Policy,2,Undisclosed conflict results in disciplinary a...,NaN,conflict_disclosed == false,HR,High
24,8,HR,Remote Work Equipment Policy,1,Company provides 1 laptop and 1 monitor,NaN,equipment_request_within_policy == true,No,Medium
25,8,HR,Remote Work Equipment Policy,2,Replacement allowed every 3 years,3.0,years_since_last_replacement >= 3,Manager,Medium

In [ ]:
df= df.drop(columns=["policy_id","rule_id"])
df["full_text"] = df.astype(str).agg(" | ".join, axis=1)
df.head()

,section,policy_name,rule_description,threshold_value,condition,approval_required,risk_level,full_text
0,Financial,Hardware Purchase Policy,Purchases up to $1500 are auto-approved,1500.0,amount <= 1500,No,Medium,Financial | Hardware Purchase Policy | Purchas...
1,Financial,Hardware Purchase Policy,Purchases between $1501–$3000 require manager ...,3000.0,1500 < amount <= 3000,Manager,Medium,Financial | Hardware Purchase Policy | Purchas...
2,Financial,Hardware Purchase Policy,"Purchases above $3000 require manager, finance...",3000.0,amount > 3000,Manager+Finance+CTO,Medium,Financial | Hardware Purchase Policy | Purchas...
3,Financial,Hardware Purchase Policy,Annual hardware budget per employee is $2500,2500.0,annual_budget_limit,No,Medium,Financial | Hardware Purchase Policy | Annual ...
4,Financial,Hardware Purchase Policy,Vendor must be selected from approved vendor list,NaN,vendor_approved == true,No,Medium,Financial | Hardware Purchase Policy | Vendor ...

In [ ]:
df["full_text"][0]

'Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium'

In [ ]:
# Target
#1) Matching row with userQ  ( Semantic Search)
#2) Matching rule with condition col. (keyword Search)

In [ ]:
#  Semantic Search

# 1) Embedding


from sentence_transformers import SentenceTransformer
import numpy as np

embedder = SentenceTransformer("all-MiniLM-L6-v2")
policy_texts = df["full_text"].tolist()

policy_embeddings = embedder.encode(
    policy_texts,
    normalize_embeddings=True
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
policy_texts[0]

'Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium'

In [ ]:
policy_embeddings[0]

array([-1.37061914e-02,  4.47236598e-02, -1.61637012e-02, -5.36067747e-02,
       -1.91182469e-03,  2.49939617e-02,  2.33572293e-02,  4.44731191e-02,
       -4.84552272e-02,  2.69257501e-02,  6.35468215e-02, -1.86100081e-02,
        6.56950194e-03, -5.27026579e-02, -8.51291865e-02, -1.72419809e-02,
        5.09684980e-02, -1.25831291e-01, -2.87466925e-02,  4.32613445e-03,
        2.74031181e-02, -3.38292122e-02, -1.66924689e-02,  1.64940860e-02,
        3.45937572e-02,  6.16535405e-03,  5.32277450e-02,  2.17648651e-02,
       -7.00197648e-03,  3.58746126e-02, -1.00474589e-01, -3.03701963e-02,
        9.29182172e-02, -5.24217673e-02,  6.00386821e-02, -7.98505619e-02,
       -6.13256879e-02, -1.00962795e-01, -3.90885957e-02, -1.18482850e-01,
        1.34699391e-02, -8.85257944e-02, -8.76408815e-02,  3.28780189e-02,
        6.45360574e-02,  2.00531203e-02, -6.23312108e-02,  6.48792461e-02,
        2.42649857e-03,  8.24130699e-02,  4.28119069e-03,  7.37885088e-02,
        4.21453267e-02, -6.58245385e-03, -2.99451221e-02,  3.84440133e-03,
        1.30249644e-02,  3.67700332e-03,  4.72688600e-02,  1.09926127e-02,
        7.75849596e-02, -8.42357054e-02, -9.10816267e-02,  3.43306549e-02,
        6.69251103e-03,  5.18853329e-02, -7.89087117e-02, -2.25784685e-02,
        5.52222249e-04,  5.18964827e-02, -3.95442965e-03, -5.21448590e-02,
       -1.57356001e-02, -4.55526781e-04,  3.40234339e-02,  7.38688698e-03,
       -3.14230658e-03, -1.93536375e-02,  6.35307729e-02, -2.48767231e-02,
       -9.47286487e-02,  1.29883131e-03, -3.50114554e-02, -6.12041019e-02,
       -6.16753800e-03,  3.25593837e-02, -4.17991132e-02,  7.47708678e-02,
        1.42485192e-02,  1.99043322e-02,  4.71731313e-02, -9.63104609e-03,
        2.59454381e-02, -4.61925194e-02,  1.22485748e-02,  1.33033339e-02,
       -7.61539629e-03, -1.78491250e-01, -2.16058828e-02, -4.29277495e-03,
        7.62266219e-02,  1.87905710e-02,  8.38772953e-03,  1.30899325e-02,
       -7.50183538e-02, -4.58435602e-02,  1.54363168e-02,  9.42639187e-02,
        3.76380198e-02,  2.43689045e-02, -5.48375659e-02, -1.90491900e-02,
        4.44396324e-02, -1.77414212e-02, -5.44678196e-02,  7.64782652e-02,
       -6.41049147e-02, -3.28449570e-02,  1.31884426e-01, -1.62037020e-03,
       -2.56959721e-02, -2.24780161e-02,  4.13913326e-03, -6.01586774e-02,
        4.34686616e-03, -4.25676219e-02, -5.06533571e-02, -1.60308648e-33,
        5.36241159e-02,  5.61969057e-02, -9.10637751e-02, -1.17208168e-01,
       -4.74773496e-02, -7.30130170e-03,  5.40583879e-02,  1.64396968e-02,
        2.77482811e-02,  5.95949665e-02, -8.48783832e-03,  1.17794201e-01,
       -3.78770977e-02,  4.89892326e-02,  5.59525043e-02, -3.36670391e-02,
       -2.06025243e-02,  4.18625474e-02,  1.11021541e-01,  6.23517185e-02,
       -8.20997544e-03, -9.07351449e-03,  6.36310652e-02,  1.72086619e-02,
        3.54730897e-02,  1.33679863e-02, -5.03691621e-02,  6.30687252e-02,
        5.17170355e-02,  6.30065128e-02,  2.24707369e-02, -2.69881431e-02,
        7.15437680e-02, -8.49419087e-02,  2.99533810e-02,  3.57631445e-02,
       -4.67738658e-02, -6.39587045e-02, -3.20815109e-03, -2.47229431e-02,
        2.48681940e-03, -1.82303749e-02, -8.17583129e-03, -4.76005189e-02,
       -5.73000349e-02,  2.71652583e-02,  2.25434103e-03, -2.31573470e-02,
       -3.69726457e-02,  1.77814849e-02, -9.08211917e-02,  3.52435187e-02,
       -6.74321353e-02, -4.51308787e-02, -5.09767085e-02, -1.75486878e-02,
        3.72615494e-02,  2.10011750e-02,  5.23093492e-02,  2.03759526e-04,
       -1.14132743e-02, -1.88318938e-02,  4.44722883e-02, -9.23532061e-03,
       -5.28701022e-02,  1.96101796e-02,  9.50335898e-03, -2.85479557e-02,
       -2.70293970e-02, -1.69661064e-02, -2.59013399e-02, -8.19034409e-03,
        1.83900092e-02,  1.00089926e-02,  4.26609963e-02,  1.88271813e-02,
       -3.04836258e-02,  1.36089912e-02, -4.29129563e-02,  5.68495430e-02,
       -8.33678320e-02,  2.18329653e-02,  4.48693447e-02,  5.71574643e-02,
        5.70508577e-02,  5.35484329e-02,  3.08012329e-02,  8.92227963e-02,
       -2.07300894e-02, -3.42761278e-02, -2.37465613e-02,  5.38902022e-02,
        1.88157167e-02,  6.35653511e-02,  6.17659017e-02, -7.79969338e-34,
       -4.39829193e-03,  9.32692438e-02,  5.54181412e-02,  5.38627431e-02,
       -5.02172187e-02,  5.49520403e-02, -5.10216802e-02,  3.06130499e-02,
        1.04477659e-01,  1.33390110e-02, -5.07910103e-02,  2.64610089e-02,
       -1.87325478e-02, -3.80476788e-02,  6.41307840e-03, -6.96953759e-02,
       -7.17893541e-02, -6.94472939e-02,  6.86594695e-02,  1.25295958e-02,
        3.01376749e-02,  1.77233722e-02, -3.87760694e-03,  8.38570446e-02,
        1.36214949e-03,  2.15295516e-02, -4.69824821e-02,  4.86657396e-02,
       -6.51175380e-02, -3.83616462e-02,  4.67545614e-02, -2.54033711e-02,
       -9.50369891e-03,  5.44059128e-02,  9.78297670e-04, -6.12576045e-02,
        7.97825381e-02,  1.03862196e-01,  2.77582891e-02,  7.47726532e-03,
        1.58981070e-01, -6.50976300e-02, -8.47889297e-03,  3.17850038e-02,
       -2.76587252e-02, -1.01941347e-01,  5.09228967e-02, -8.85770693e-02,
        3.46235335e-02, -5.50344773e-02, -6.10548556e-02, -6.15557171e-02,
        8.82463008e-02,  5.83593398e-02, -3.21238786e-02,  7.90617391e-02,
        1.71850026e-01,  9.63179171e-02, -2.66138967e-02, -2.16129934e-03,
       -6.06220274e-04,  3.43991444e-02,  5.66510223e-02,  4.08925861e-02,
       -8.49724747e-03, -8.01556855e-02,  2.41055079e-02, -3.01239695e-02,
        6.36689365e-02, -7.89667387e-03,  1.11828828e-02, -2.23842841e-02,
        4.37057614e-02,  1.98213868e-02, -2.18183314e-03, -2.80882744e-03,
        9.95282736e-03, -6.83444515e-02,  1.66224595e-02, -3.51763926e-02,
       -2.57379860e-02,  4.35961224e-02,  1.11541422e-02,  7.58869797e-02,
       -6.80759251e-02, -7.30515495e-02, -4.84510362e-02, -3.91927958e-02,
       -3.37827690e-02,  7.31194690e-02, -6.99354708e-02,  7.51360739e-03,
       -3.11336257e-02, -3.02075632e-02, -9.46883485e-02, -2.64027111e-08,
        3.66870798e-02,  1.25970750e-03,  6.02690093e-02,  7.45652318e-02,
       -6.37003873e-03, -2.01913454e-02, -2.76509766e-02,  1.10728072e-03,
       -4.52760570e-02, -4.55917530e-02,  6.08952977e-02, -2.99530942e-02,
       -6.73857033e-02, -8.76627490e-02, -8.56613964e-02, -3.65541875e-02,
        3.60631719e-02,  7.90579468e-02, -4.26989757e-02,  2.97986679e-02,
       -2.74400618e-02,  3.48251648e-02,  2.65743546e-02, -2.82726381e-02,
       -3.22299972e-02,  4.58230264e-03, -4.17713949e-04,  8.82456824e-02,
        2.96633560e-02,  4.89025451e-02, -1.98553726e-02,  1.95344090e-02,
        7.81783462e-02, -4.74390574e-02, -1.60700995e-02, -5.14232069e-02,
       -2.18778178e-02, -2.17265636e-02,  4.19855230e-02, -6.59076273e-02,
        1.63427815e-02, -8.29663053e-02, -4.82516028e-02, -6.45800307e-02,
       -9.82352346e-03,  2.80468650e-02, -1.28407121e-01, -9.30986851e-02,
        4.27073501e-02,  4.90473844e-02,  6.37451783e-02, -2.00265367e-02,
        4.86570075e-02,  4.13084067e-02, -2.95809563e-02, -6.76779300e-02,
        7.07743550e-03,  1.29999826e-02, -4.23749909e-02, -3.67193148e-02,
       -6.90667098e-03, -4.00284156e-02,  7.11859390e-03, -2.43885107e-02],
      dtype=float32)

In [ ]:
userQ =  "i need left form my job in 3 Days"
userQ = "I need buy device with 4500$"

userQ_embedding = embedder.encode(
    [userQ],
    normalize_embeddings=True
)

In [ ]:
# userQ_embedding  and policy_embeddings

In [ ]:
score = (  userQ_embedding @ policy_embeddings.T).squeeze()

# Cosine Similarity apply with normalize_embeddings=True in embedder.encode()
# score = (userQ_embedding @ policy_embeddings.T).squeeze() / (
  #  np.linalg.norm(userQ_embedding) *
 #   np.linalg.norm(policy_embeddings, axis=1)
# )

top_k = 5
top_idx = np.argsort(-score)[:top_k]

for i in top_idx:
    print("Score:", round(score[i], 3))
    print("Text :", df.iloc[i]["full_text"])
    print("-"*60)

Score: 0.478
Text : Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium
------------------------------------------------------------
Score: 0.369
Text : Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium
------------------------------------------------------------
Score: 0.357
Text : Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium
------------------------------------------------------------
Score: 0.311
Text : Financial | Hardware Purchase Policy | Annual hardware budget per employee is $2500 | 2500.0 | annual_budget_limit | No | Medium
------------------------------------------------------------
Score: 0.263
Text : Financial | Hardware Purchase Policy | Vendor must be selected from approved vendor list | nan | vendor_approved == true | No | Medium
------------------------------------------------------------

In [ ]:
def retrive_cand(userQ,policy_embeddings):
  out = []
  userQ_embedding = embedder.encode(
    [userQ],
    normalize_embeddings=True
  )
  score = (  userQ_embedding @ policy_embeddings.T).squeeze()
  top_k = 5
  top_idx = np.argsort(-score)[:top_k]
  for i in top_idx:
    #  print("Score:", round(score[i], 3))

    out.append({ "Score":round(score[i], 3)  ,  "full_text":df.iloc[i]["full_text"]})
     # print("Text :", df.iloc[i]["full_text"])
    #  print("-"*60)
  return out

In [ ]:
userQ =  "i need left form my job in 3 Days"
retrive_cand(userQ,policy_embeddings)

[{'Score': np.float32(0.241),
  'full_text': 'Legal | Contract Termination Policy | Contracts must include minimum 30-day termination notice | 30.0 | termination_notice_days >= 30 | Legal | High'},
 {'Score': np.float32(0.239),
  'full_text': 'HR | Remote Work Equipment Policy | Replacement allowed every 3 years | 3.0 | years_since_last_replacement >= 3 | Manager | Medium'},
 {'Score': np.float32(0.161),
  'full_text': 'Legal | Contract Termination Policy | Indemnification clauses must be reviewed by legal | nan | indemnification_clause == true | Legal | High'},
 {'Score': np.float32(0.158),
  'full_text': 'Legal | Vendor Agreement Policy | Payment terms must not exceed Net 60 unless CFO approval | 60.0 | payment_terms_days <= 60 | CFO_if_exceeds | High'},
 {'Score': np.float32(0.152),
  'full_text': 'Legal | Contract Termination Policy | Liability cap must not exceed 12 months of contract value | 12.0 | liability_cap_months <= 12 | Legal | High'}]

In [ ]:
userQ = "I need buy device with 4500$"
top5Cand = retrive_cand(userQ,policy_embeddings)
top5Cand

[{'Score': np.float32(0.478),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium'},
 {'Score': np.float32(0.369),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium'},
 {'Score': np.float32(0.357),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium'},
 {'Score': np.float32(0.311),
  'full_text': 'Financial | Hardware Purchase Policy | Annual hardware budget per employee is $2500 | 2500.0 | annual_budget_limit | No | Medium'},
 {'Score': np.float32(0.263),
  'full_text': 'Financial | Hardware Purchase Policy | Vendor must be selected from approved vendor list | nan | vendor_approved == true | No | Medium'}]

In [ ]:
# 2) Matching rule with condition col. (keyword Search)

# A) extract number form userQ
# B) extract cond from full text in top5 cand
# C) check cond ???

In [ ]:
import re

def extract_amount(text):
    match = re.search(r'[\d,]+', text)
    if match:
        return int(match.group().replace(",", ""))
    return None

amount_userQ = extract_amount(userQ)
amount_userQ

4500

In [ ]:
def fullsystem(userQ,policy_embeddings):
  out = []
  amount_userQ = extract_amount(userQ) # 1

  userQ_embedding = embedder.encode(
    [userQ],
    normalize_embeddings=True
  )
  score = (  userQ_embedding @ policy_embeddings.T).squeeze()
  top_k = 5
  top_idx = np.argsort(-score)[:top_k]
  num = 0
  matched = []
  for i in top_idx:
   # print(f"----------- top {num+1} -----------")
    condition = df.iloc[i]["condition"]
    #print(condition)
    expr= condition.replace("amount",str(amount_userQ))
    #print(expr)
    try:
      if eval(expr) == True:
        matched.append({ "Score":round(score[i], 3)  ,  "full_text":df.iloc[i]["full_text"]})

    except:
      pass
    num +=1

  return matched

In [ ]:
userQ = "I need buy device with 4500$"

fullsystem(userQ,policy_embeddings)

[{'Score': np.float32(0.357),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium'}]

In [ ]:
userQ = "I need buy device with 1000$"

fullsystem(userQ,policy_embeddings)

[{'Score': np.float32(0.34),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium'}]

In [ ]:
userQ = "I need buy device with 2500$"

fullsystem(userQ,policy_embeddings)

[{'Score': np.float32(0.437),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium'}]

In [ ]:
# Task 1
# top5 to LLM >> and get top 1 matching to userQ


# Task 2:
# Handle flight_hours prog. & amount