In [1]:
# Dependency Installation (Moved to top for best practice)
!pip install bitsandbytes accelerate transformers --upgrade --force-reinstall

# Mount Google Drive (if using Colab)
try:
    from google.colab import drive
    drive.mount('/content/drive')
    IN_COLAB = True
except:
    IN_COLAB = False
    print("Not running in Colab")

Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting transformers
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Collecting torch<3,>=2.3 (from bitsandbytes)
  Downloading torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (31 kB)
Collecting numpy>=1.17 (from bitsandbytes)
  Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting packaging>=20.9 (from bitsandbytes)
  Downloading packaging-26.0-py3-none-any.whl.metadata (3.3 kB)
Collecting psutil (from accelerate)
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Collecting pyyaml (from accelerate)
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting huggingface_hub>=0.21.0 (from accelerate)
  Downloading huggingface_hub-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting safetensors>=0.4.3 (from accelerate)
  Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2026.2.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 3.0 MB/s eta 0:00:00
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting tqdm>=4.27 (from transformers)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 5.5 MB/s eta 0:00:00
Collecting filelock>=3.10.0 (from huggingface_hub>=0.21.0->accelerate)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface_hub>=0.21.0->accelerate)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface_hub>=0.21.0->accelerate)
  Downloading hf_xet-1.4.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface_hub>=0.21.0->accelerate)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting typing-extensions>=4.1.0 (from huggingface_hub>=0.21.0->accelerate)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools (from torch<3,>=2.3->bitsandbytes)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting sympy>=1.13.3 (from torch<3,>=2.3->bitsandbytes)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch<3,>=2.3->bitsandbytes)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch<3,>=2.3->bitsandbytes)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting cuda-bindings==12.9.4 (from torch<3,>=2.3->bitsandbytes)
  Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.4.5 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch<3,>=2.3->bitsandbytes)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.6.0 (from torch<3,>=2.3->bitsandbytes)
  Downloading triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings==12.9.4->torch<3,>=2.3->bitsandbytes)
  Downloading cuda_pathfinder-1.4.2-py3-none-any.whl.metadata (1.9 kB)
Collecting click>=8.2.1 (from typer->transformers)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->transformers)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Downloading anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Collecting certifi (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->transformers)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=12.3.0->typer->transformers)
  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch<3,>=2.3->bitsandbytes)
  Downloading markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.7 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 13.0 MB/s eta 0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 30.1 MB/s eta 0:00:00
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 93.1 MB/s eta 0:00:00
Downloading huggingface_hub-1.7.1-py3-none-any.whl (616 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 616.3/616.3 kB 46.1 MB/s eta 0:00:00
Downloading numpy-2.4.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 77.5 MB/s eta 0:00:00
Downloading packaging-26.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 8.9 MB/s eta 0:00:00
Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 49.1 MB/s eta 0:00:00
Downloading regex-2026.2.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (802 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 802.0/802.0 kB 46.7 MB/s eta 0:00:00
Downloading safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.2/507.2 kB 31.4 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 81.7 MB/s eta 0:00:00
Downloading torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl (915.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 915.6/915.6 MB 1.1 MB/s eta 0:00:00
Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 94.9 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 1.1 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 92.0 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 10.1 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 65.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 6.3 MB/s eta 0:00:00
Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 69.6 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 13.0 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 1.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 5.1 MB/s eta 0:00:00
Downloading nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.2/287.2 MB 5.8 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.3/322.3 MB 4.6 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 16.4 MB/s eta 0:00:00
Downloading nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (139.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.1/139.1 MB 7.8 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 10.1 MB/s eta 0:00:00
Downloading triton-3.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.3/188.3 MB 6.9 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 8.9 MB/s eta 0:00:00
Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 14.4 MB/s eta 0:00:00
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.1/56.1 kB 5.3 MB/s eta 0:00:00
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.3/108.3 kB 13.6 MB/s eta 0:00:00
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.5/202.5 kB 19.6 MB/s eta 0:00:00
Downloading hf_xet-1.4.2-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 57.9 MB/s eta 0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 9.7 MB/s eta 0:00:00
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 10.1 MB/s eta 0:00:00
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 53.1 MB/s eta 0:00:00
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.5/310.5 kB 28.9 MB/s eta 0:00:00
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 58.4 MB/s eta 0:00:00
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 5.1 MB/s eta 0:00:00
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 16.5 MB/s eta 0:00:00
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 45.1 MB/s eta 0:00:00
Downloading cuda_pathfinder-1.4.2-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 5.4 MB/s eta 0:00:00
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.3/87.3 kB 9.9 MB/s eta 0:00:00
Downloading markupsafe-3.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 32.1 MB/s eta 0:00:00
Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 46.4 MB/s eta 0:00:00
Downloading anyio-4.12.1-py3-none-any.whl (113 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.6/113.6 kB 13.4 MB/s eta 0:00:00
Downloading idna-3.11-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 8.2 MB/s eta 0:00:00
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.7/153.7 kB 14.6 MB/s eta 0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: nvidia-cusparselt-cu12, mpmath, typing-extensions, triton, tqdm, sympy, shellingham, setuptools, safetensors, regex, pyyaml, pygments, psutil, packaging, nvidia-nvtx-cu12, nvidia-nvshmem-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, networkx, mdurl, MarkupSafe, idna, hf-xet, h11, fsspec, filelock, cuda-pathfinder, click, certifi, annotated-doc, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, markdown-it-py, jinja2, httpcore, cuda-bindings, anyio, rich, nvidia-cusolver-cu12, httpx, typer, torch, huggingface_hub, bitsandbytes, tokenizers, accelerate, transformers
  Attempting uninstall: nvidia-cusparselt-cu12
    Found existing installation: nvidia-cusparselt-cu12 0.7.1
    Uninstalling nvidia-cusparselt-cu12-0.7.1:
      Successfully uninstalled nvidia-cusparselt-cu12-0.7.1
  Attempting uninstall: mpmath
    Found existing installation: mpmath 1.3.0
    Uninstalling mpmath-1.3.0:
      Successfully uninstalled mpmath-1.3.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
  Attempting uninstall: shellingham
    Found existing installation: shellingham 1.5.4
    Uninstalling shellingham-1.5.4:
      Successfully uninstalled shellingham-1.5.4
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.7.0
    Uninstalling safetensors-0.7.0:
      Successfully uninstalled safetensors-0.7.0
  Attempting uninstall: regex
    Found existing installation: regex 2025.11.3
    Uninstalling regex-2025.11.3:
      Successfully uninstalled regex-2025.11.3
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: pygments
    Found existing installation: Pygments 2.19.2
    Uninstalling Pygments-2.19.2:
      Successfully uninstalled Pygments-2.19.2
  Attempting uninstall: psutil
    Found existing installation: psutil 5.9.5
    Uninstalling psutil-5.9.5:
      Successfully uninstalled psutil-5.9.5
  Attempting uninstall: packaging
    Found existing installation: packaging 26.0
    Uninstalling packaging-26.0:
      Successfully uninstalled packaging-26.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.8.90
    Uninstalling nvidia-nvtx-cu12-12.8.90:
      Successfully uninstalled nvidia-nvtx-cu12-12.8.90
  Attempting uninstall: nvidia-nvshmem-cu12
    Found existing installation: nvidia-nvshmem-cu12 3.4.5
    Uninstalling nvidia-nvshmem-cu12-3.4.5:

Not running in Colab

# [GPT Link](https://chatgpt.com/share/69b327a6-da94-8005-80c3-f7f09081bc40)

## [Word File](https://docs.google.com/document/d/1ufwWzABa8MhAhmbVzq7El8mLDy3Ra8m-l1jWfWW9ZRE/edit?usp=sharing)

# [Policy_en CSV Link](https://drive.google.com/file/d/17ShQTtD0Ryy6wycrrLfkJ3Ak-80nkp-v/view?usp=sharing)

In [1]:
import pandas as pd
Policy_Csv = "/content/Policy_en.csv"
df = pd.read_csv(Policy_Csv)
df

,policy_id,section,policy_name,rule_id,rule_description,threshold_value,condition,approval_required,risk_level
0,1,Financial,Hardware Purchase Policy,1,Purchases up to $1500 are auto-approved,1500.0,amount <= 1500,No,Medium
1,1,Financial,Hardware Purchase Policy,2,Purchases between $1501–$3000 require manager ...,3000.0,1500 < amount <= 3000,Manager,Medium
2,1,Financial,Hardware Purchase Policy,3,"Purchases above $3000 require manager, finance...",3000.0,amount > 3000,Manager+Finance+CTO,Medium
3,1,Financial,Hardware Purchase Policy,4,Annual hardware budget per employee is $2500,2500.0,annual_budget_limit,No,Medium
4,1,Financial,Hardware Purchase Policy,5,Vendor must be selected from approved vendor list,NaN,vendor_approved == true,No,Medium
5,2,Financial,Travel Expense Policy,1,Economy class required for flights under 6 hours,6.0,flight_hours <= 6,No,Medium
6,2,Financial,Travel Expense Policy,2,Business class allowed for flights over 6 hour...,6.0,flight_hours > 6 AND role == executive,Manager,Medium
7,2,Financial,Travel Expense Policy,3,Hotel cost must not exceed $250 regional,250.0,region == regional,No,Medium
8,2,Financial,Travel Expense Policy,4,Hotel cost must not exceed $400 international ...,400.0,region == international,No,Medium
9,2,Financial,Travel Expense Policy,5,Receipts mandatory for reimbursement,NaN,receipt_provided == true,No,Medium
10,3,Security,Software Installation Policy,1,Only software from approved registry allowed,NaN,software_approved == true,IT,High
11,3,Security,Software Installation Policy,2,SaaS handling customer data requires security ...,NaN,handles_customer_data == true,Security+Legal,High
12,3,Security,Software Installation Policy,3,No pirated software allowed,NaN,software_legitimate == true,IT,High
13,4,Security,Data Handling Policy,1,Restricted data must be encrypted at rest,NaN,data_classification == restricted,Security,Critical
14,4,Security,Data Handling Policy,2,Restricted data must not be shared via email,NaN,data_shared_email == false,Security,Critical
15,4,Security,Data Handling Policy,3,External sharing requires legal approval,NaN,external_sharing == true,Legal,Critical
16,5,Legal,Contract Termination Policy,1,Contracts must include minimum 30-day terminat...,30.0,termination_notice_days >= 30,Legal,High
17,5,Legal,Contract Termination Policy,2,Liability cap must not exceed 12 months of con...,12.0,liability_cap_months <= 12,Legal,High
18,5,Legal,Contract Termination Policy,3,Indemnification clauses must be reviewed by legal,NaN,indemnification_clause == true,Legal,High
19,6,Legal,Vendor Agreement Policy,1,Vendor must pass compliance screening,NaN,vendor_screened == true,Compliance,High
20,6,Legal,Vendor Agreement Policy,2,Vendors processing customer data must comply w...,NaN,processes_customer_data == true,Legal,High
21,6,Legal,Vendor Agreement Policy,3,Payment terms must not exceed Net 60 unless CF...,60.0,payment_terms_days <= 60,CFO_if_exceeds,High
22,7,HR,Conflict of Interest Policy,1,Employees must disclose financial interest in ...,NaN,conflict_disclosed == true,HR,High
23,7,HR,Conflict of Interest Policy,2,Undisclosed conflict results in disciplinary a...,NaN,conflict_disclosed == false,HR,High
24,8,HR,Remote Work Equipment Policy,1,Company provides 1 laptop and 1 monitor,NaN,equipment_request_within_policy == true,No,Medium
25,8,HR,Remote Work Equipment Policy,2,Replacement allowed every 3 years,3.0,years_since_last_replacement >= 3,Manager,Medium

In [2]:
df= df.drop(columns=["policy_id","rule_id"])
df["full_text"] = df.astype(str).agg(" | ".join, axis=1)
df.head()

,section,policy_name,rule_description,threshold_value,condition,approval_required,risk_level,full_text
0,Financial,Hardware Purchase Policy,Purchases up to $1500 are auto-approved,1500.0,amount <= 1500,No,Medium,Financial | Hardware Purchase Policy | Purchas...
1,Financial,Hardware Purchase Policy,Purchases between $1501–$3000 require manager ...,3000.0,1500 < amount <= 3000,Manager,Medium,Financial | Hardware Purchase Policy | Purchas...
2,Financial,Hardware Purchase Policy,"Purchases above $3000 require manager, finance...",3000.0,amount > 3000,Manager+Finance+CTO,Medium,Financial | Hardware Purchase Policy | Purchas...
3,Financial,Hardware Purchase Policy,Annual hardware budget per employee is $2500,2500.0,annual_budget_limit,No,Medium,Financial | Hardware Purchase Policy | Annual ...
4,Financial,Hardware Purchase Policy,Vendor must be selected from approved vendor list,NaN,vendor_approved == true,No,Medium,Financial | Hardware Purchase Policy | Vendor ...

In [75]:
userQ = "I want to book a business class flight for 10 hours as an executive"
top5 = retrive_cand(userQ, policy_embeddings)

print(f"--- Logic Answer (fullsystem) ---")
print(fullsystem(userQ, policy_embeddings))

print(f"\n--- Clean Summary Answer ---")
print(get_llm_best_policy(userQ, top5))

--- Logic Answer (fullsystem) ---
MATCHED POLICY: Financial | Travel Expense Policy | Business class allowed for flights over 6 hours for executive-level employees | 6.0 | flight_hours > 6 AND role == executive | Manager | Medium

--- Clean Summary Answer ---
Based on the Travel Expense Policy: Business class allowed for flights over 6 hours for executive-level employees. Approval Required: Manager.

In [3]:
df["full_text"][0]

'Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium'

In [ ]:
# Target
#1) Matching row with userQ  ( Semantic Search)
#2) Matching rule with condition col. (keyword Search)

In [4]:
#  Semantic Search

# 1) Embedding


from sentence_transformers import SentenceTransformer
import numpy as np

embedder = SentenceTransformer("all-MiniLM-L6-v2")
policy_texts = df["full_text"].tolist()

policy_embeddings = embedder.encode(
    policy_texts,
    normalize_embeddings=True
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [5]:
policy_texts[0]

'Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium'

In [6]:
policy_embeddings[0]

array([-1.37061914e-02,  4.47236598e-02, -1.61637012e-02, -5.36067747e-02,
       -1.91182469e-03,  2.49939617e-02,  2.33572293e-02,  4.44731191e-02,
       -4.84552272e-02,  2.69257501e-02,  6.35468215e-02, -1.86100081e-02,
        6.56950194e-03, -5.27026579e-02, -8.51291865e-02, -1.72419809e-02,
        5.09684980e-02, -1.25831291e-01, -2.87466925e-02,  4.32613445e-03,
        2.74031181e-02, -3.38292122e-02, -1.66924689e-02,  1.64940860e-02,
        3.45937572e-02,  6.16535405e-03,  5.32277450e-02,  2.17648651e-02,
       -7.00197648e-03,  3.58746126e-02, -1.00474589e-01, -3.03701963e-02,
        9.29182172e-02, -5.24217673e-02,  6.00386821e-02, -7.98505619e-02,
       -6.13256879e-02, -1.00962795e-01, -3.90885957e-02, -1.18482850e-01,
        1.34699391e-02, -8.85257944e-02, -8.76408815e-02,  3.28780189e-02,
        6.45360574e-02,  2.00531203e-02, -6.23312108e-02,  6.48792461e-02,
        2.42649857e-03,  8.24130699e-02,  4.28119069e-03,  7.37885088e-02,
        4.21453267e-02, -6.58245385e-03, -2.99451221e-02,  3.84440133e-03,
        1.30249644e-02,  3.67700332e-03,  4.72688600e-02,  1.09926127e-02,
        7.75849596e-02, -8.42357054e-02, -9.10816267e-02,  3.43306549e-02,
        6.69251103e-03,  5.18853329e-02, -7.89087117e-02, -2.25784685e-02,
        5.52222249e-04,  5.18964827e-02, -3.95442965e-03, -5.21448590e-02,
       -1.57356001e-02, -4.55526781e-04,  3.40234339e-02,  7.38688698e-03,
       -3.14230658e-03, -1.93536375e-02,  6.35307729e-02, -2.48767231e-02,
       -9.47286487e-02,  1.29883131e-03, -3.50114554e-02, -6.12041019e-02,
       -6.16753800e-03,  3.25593837e-02, -4.17991132e-02,  7.47708678e-02,
        1.42485192e-02,  1.99043322e-02,  4.71731313e-02, -9.63104609e-03,
        2.59454381e-02, -4.61925194e-02,  1.22485748e-02,  1.33033339e-02,
       -7.61539629e-03, -1.78491250e-01, -2.16058828e-02, -4.29277495e-03,
        7.62266219e-02,  1.87905710e-02,  8.38772953e-03,  1.30899325e-02,
       -7.50183538e-02, -4.58435602e-02,  1.54363168e-02,  9.42639187e-02,
        3.76380198e-02,  2.43689045e-02, -5.48375659e-02, -1.90491900e-02,
        4.44396324e-02, -1.77414212e-02, -5.44678196e-02,  7.64782652e-02,
       -6.41049147e-02, -3.28449570e-02,  1.31884426e-01, -1.62037020e-03,
       -2.56959721e-02, -2.24780161e-02,  4.13913326e-03, -6.01586774e-02,
        4.34686616e-03, -4.25676219e-02, -5.06533571e-02, -1.60308648e-33,
        5.36241159e-02,  5.61969057e-02, -9.10637751e-02, -1.17208168e-01,
       -4.74773496e-02, -7.30130170e-03,  5.40583879e-02,  1.64396968e-02,
        2.77482811e-02,  5.95949665e-02, -8.48783832e-03,  1.17794201e-01,
       -3.78770977e-02,  4.89892326e-02,  5.59525043e-02, -3.36670391e-02,
       -2.06025243e-02,  4.18625474e-02,  1.11021541e-01,  6.23517185e-02,
       -8.20997544e-03, -9.07351449e-03,  6.36310652e-02,  1.72086619e-02,
        3.54730897e-02,  1.33679863e-02, -5.03691621e-02,  6.30687252e-02,
        5.17170355e-02,  6.30065128e-02,  2.24707369e-02, -2.69881431e-02,
        7.15437680e-02, -8.49419087e-02,  2.99533810e-02,  3.57631445e-02,
       -4.67738658e-02, -6.39587045e-02, -3.20815109e-03, -2.47229431e-02,
        2.48681940e-03, -1.82303749e-02, -8.17583129e-03, -4.76005189e-02,
       -5.73000349e-02,  2.71652583e-02,  2.25434103e-03, -2.31573470e-02,
       -3.69726457e-02,  1.77814849e-02, -9.08211917e-02,  3.52435187e-02,
       -6.74321353e-02, -4.51308787e-02, -5.09767085e-02, -1.75486878e-02,
        3.72615494e-02,  2.10011750e-02,  5.23093492e-02,  2.03759526e-04,
       -1.14132743e-02, -1.88318938e-02,  4.44722883e-02, -9.23532061e-03,
       -5.28701022e-02,  1.96101796e-02,  9.50335898e-03, -2.85479557e-02,
       -2.70293970e-02, -1.69661064e-02, -2.59013399e-02, -8.19034409e-03,
        1.83900092e-02,  1.00089926e-02,  4.26609963e-02,  1.88271813e-02,
       -3.04836258e-02,  1.36089912e-02, -4.29129563e-02,  5.68495430e-02,
       -8.33678320e-02,  2.18329653e-02,  4.48693447e-02,  5.71574643e-02,
        5.70508577e-02,  5.35484329e-02,  3.08012329e-02,  8.92227963e-02,
       -2.07300894e-02, -3.42761278e-02, -2.37465613e-02,  5.38902022e-02,
        1.88157167e-02,  6.35653511e-02,  6.17659017e-02, -7.79969338e-34,
       -4.39829193e-03,  9.32692438e-02,  5.54181412e-02,  5.38627431e-02,
       -5.02172187e-02,  5.49520403e-02, -5.10216802e-02,  3.06130499e-02,
        1.04477659e-01,  1.33390110e-02, -5.07910103e-02,  2.64610089e-02,
       -1.87325478e-02, -3.80476788e-02,  6.41307840e-03, -6.96953759e-02,
       -7.17893541e-02, -6.94472939e-02,  6.86594695e-02,  1.25295958e-02,
        3.01376749e-02,  1.77233722e-02, -3.87760694e-03,  8.38570446e-02,
        1.36214949e-03,  2.15295516e-02, -4.69824821e-02,  4.86657396e-02,
       -6.51175380e-02, -3.83616462e-02,  4.67545614e-02, -2.54033711e-02,
       -9.50369891e-03,  5.44059128e-02,  9.78297670e-04, -6.12576045e-02,
        7.97825381e-02,  1.03862196e-01,  2.77582891e-02,  7.47726532e-03,
        1.58981070e-01, -6.50976300e-02, -8.47889297e-03,  3.17850038e-02,
       -2.76587252e-02, -1.01941347e-01,  5.09228967e-02, -8.85770693e-02,
        3.46235335e-02, -5.50344773e-02, -6.10548556e-02, -6.15557171e-02,
        8.82463008e-02,  5.83593398e-02, -3.21238786e-02,  7.90617391e-02,
        1.71850026e-01,  9.63179171e-02, -2.66138967e-02, -2.16129934e-03,
       -6.06220274e-04,  3.43991444e-02,  5.66510223e-02,  4.08925861e-02,
       -8.49724747e-03, -8.01556855e-02,  2.41055079e-02, -3.01239695e-02,
        6.36689365e-02, -7.89667387e-03,  1.11828828e-02, -2.23842841e-02,
        4.37057614e-02,  1.98213868e-02, -2.18183314e-03, -2.80882744e-03,
        9.95282736e-03, -6.83444515e-02,  1.66224595e-02, -3.51763926e-02,
       -2.57379860e-02,  4.35961224e-02,  1.11541422e-02,  7.58869797e-02,
       -6.80759251e-02, -7.30515495e-02, -4.84510362e-02, -3.91927958e-02,
       -3.37827690e-02,  7.31194690e-02, -6.99354708e-02,  7.51360739e-03,
       -3.11336257e-02, -3.02075632e-02, -9.46883485e-02, -2.64027111e-08,
        3.66870798e-02,  1.25970750e-03,  6.02690093e-02,  7.45652318e-02,
       -6.37003873e-03, -2.01913454e-02, -2.76509766e-02,  1.10728072e-03,
       -4.52760570e-02, -4.55917530e-02,  6.08952977e-02, -2.99530942e-02,
       -6.73857033e-02, -8.76627490e-02, -8.56613964e-02, -3.65541875e-02,
        3.60631719e-02,  7.90579468e-02, -4.26989757e-02,  2.97986679e-02,
       -2.74400618e-02,  3.48251648e-02,  2.65743546e-02, -2.82726381e-02,
       -3.22299972e-02,  4.58230264e-03, -4.17713949e-04,  8.82456824e-02,
        2.96633560e-02,  4.89025451e-02, -1.98553726e-02,  1.95344090e-02,
        7.81783462e-02, -4.74390574e-02, -1.60700995e-02, -5.14232069e-02,
       -2.18778178e-02, -2.17265636e-02,  4.19855230e-02, -6.59076273e-02,
        1.63427815e-02, -8.29663053e-02, -4.82516028e-02, -6.45800307e-02,
       -9.82352346e-03,  2.80468650e-02, -1.28407121e-01, -9.30986851e-02,
        4.27073501e-02,  4.90473844e-02,  6.37451783e-02, -2.00265367e-02,
        4.86570075e-02,  4.13084067e-02, -2.95809563e-02, -6.76779300e-02,
        7.07743550e-03,  1.29999826e-02, -4.23749909e-02, -3.67193148e-02,
       -6.90667098e-03, -4.00284156e-02,  7.11859390e-03, -2.43885107e-02],
      dtype=float32)

In [ ]:
# userQ_embedding  and policy_embeddings

In [ ]:
# This is an empty cell, marking as a placeholder.

In [10]:
def retrive_cand(userQ,policy_embeddings):
  out = []
  userQ_embedding = embedder.encode(
    [userQ],
    normalize_embeddings=True
  )
  score = (  userQ_embedding @ policy_embeddings.T).squeeze()
  top_k = 5
  top_idx = np.argsort(-score)[:top_k]
  for i in top_idx:
    #  print("Score:", round(score[i], 3))

    out.append({ "Score":round(score[i], 3)  ,  "full_text":df.iloc[i]["full_text"]})
     # print("Text :", df.iloc[i]["full_text"])
    #  print("-"*60)
  return out

In [11]:
userQ = "I need buy device with 4500$" # Example user query
userQ_embedding = embedder.encode(
    [userQ],
    normalize_embeddings=True
)

score = (userQ_embedding @ policy_embeddings.T).squeeze()

# Cosine Similarity apply with normalize_embeddings=True in embedder.encode()
# score = (userQ_embedding @ policy_embeddings.T).squeeze() / (
  #  np.linalg.norm(userQ_embedding) *
 #   np.linalg.norm(policy_embeddings, axis=1)
# )

top_k = 5
top_idx = np.argsort(-score)[:top_k]

for i in top_idx:
    print("Score:", round(score[i], 3))
    print("Text :", df.iloc[i]["full_text"])
    print("-"*60)

Score: 0.478
Text : Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium
------------------------------------------------------------
Score: 0.369
Text : Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium
------------------------------------------------------------
Score: 0.357
Text : Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium
------------------------------------------------------------
Score: 0.311
Text : Financial | Hardware Purchase Policy | Annual hardware budget per employee is $2500 | 2500.0 | annual_budget_limit | No | Medium
------------------------------------------------------------
Score: 0.263
Text : Financial | Hardware Purchase Policy | Vendor must be selected from approved vendor list | nan | vendor_approved == true | No | Medium
------------------------------------------------------------

In [12]:
userQ =  "i need left form my job in 3 Days"
retrive_cand(userQ,policy_embeddings)

[{'Score': np.float32(0.241),
  'full_text': 'Legal | Contract Termination Policy | Contracts must include minimum 30-day termination notice | 30.0 | termination_notice_days >= 30 | Legal | High'},
 {'Score': np.float32(0.239),
  'full_text': 'HR | Remote Work Equipment Policy | Replacement allowed every 3 years | 3.0 | years_since_last_replacement >= 3 | Manager | Medium'},
 {'Score': np.float32(0.161),
  'full_text': 'Legal | Contract Termination Policy | Indemnification clauses must be reviewed by legal | nan | indemnification_clause == true | Legal | High'},
 {'Score': np.float32(0.158),
  'full_text': 'Legal | Vendor Agreement Policy | Payment terms must not exceed Net 60 unless CFO approval | 60.0 | payment_terms_days <= 60 | CFO_if_exceeds | High'},
 {'Score': np.float32(0.152),
  'full_text': 'Legal | Contract Termination Policy | Liability cap must not exceed 12 months of contract value | 12.0 | liability_cap_months <= 12 | Legal | High'}]

In [13]:
userQ = "I need buy device with 4500$"
top5Cand = retrive_cand(userQ,policy_embeddings)
top5Cand

[{'Score': np.float32(0.478),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium'},
 {'Score': np.float32(0.369),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium'},
 {'Score': np.float32(0.357),
  'full_text': 'Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium'},
 {'Score': np.float32(0.311),
  'full_text': 'Financial | Hardware Purchase Policy | Annual hardware budget per employee is $2500 | 2500.0 | annual_budget_limit | No | Medium'},
 {'Score': np.float32(0.263),
  'full_text': 'Financial | Hardware Purchase Policy | Vendor must be selected from approved vendor list | nan | vendor_approved == true | No | Medium'}]

In [14]:
# This is an empty cell, marking as a placeholder.

In [15]:
# 2) Matching rule with condition col. (keyword Search)

# A) extract number form userQ
# B) extract cond from full text in top5 cand
# C) check cond ???

In [16]:
import re

def extract_numbers(text):
    # Extract all numbers, including those with commas, from the text
    numbers = re.findall(r'\b(?:\d{{1,3}}(?:,\d{{3}})*|\d+)(?:\.\d+)?\b', text.replace('$', ''))
    # Convert to float or int, handle potential commas
    return [float(n.replace(',', '')) if '.' in n else int(n.replace(',', '')) for n in numbers]

# The previous `amount_userQ` was specific to an 'amount'.
# We will now handle numerical extraction more generically within `fullsystem`.

In [59]:
def fullsystem(userQ, policy_embeddings):
  user_numbers = extract_numbers(userQ)
  userQ_embedding = embedder.encode([userQ], normalize_embeddings=True)
  score = (userQ_embedding @ policy_embeddings.T).squeeze()

  # Get the top 5 candidates to find the best logical match
  top_idx = np.argsort(-score)[:5]

  best_match = None
  for i in top_idx:
    policy_full_text = df.iloc[i]['full_text']
    condition_str = str(df.iloc[i]['condition'])
    policy_name = df.iloc[i]['policy_name']
    rule_description = df.iloc[i]['rule_description']
    threshold_value = df.iloc[i]['threshold_value']

    eval_vars = {
        'amount': user_numbers[0] if user_numbers else None,
        'flight_hours': user_numbers[0] if user_numbers else None,
        'hotel_cost': user_numbers[0] if user_numbers else None,
        'termination_notice_days': user_numbers[0] if user_numbers else None,
        'payment_terms_days': user_numbers[0] if user_numbers else None,
        'years_since_last_replacement': user_numbers[0] if user_numbers else None,
        'true': True, 'false': False, 'executive': 'executive', 'international': 'international', 'regional': 'regional'
    }
    eval_vars['role'] = 'executive' if 'executive' in userQ.lower() else ''
    eval_vars['region'] = 'international' if 'international' in userQ.lower() else ('regional' if 'regional' in userQ.lower() else '')

    condition_to_eval = condition_str.replace(' AND ', ' and ').replace(' OR ', ' or ')

    try:
        # Check if condition is met
        if eval(condition_to_eval, {'__builtins__': {}}, eval_vars) == True:
            best_match = f"MATCHED POLICY: {policy_full_text}"
            break
    except:
        continue

  return best_match if best_match else "No exact policy match found for the criteria provided."

In [39]:
userQ = "I need buy device with 4500$"

results = fullsystem(userQ, policy_embeddings)
print(f"--- User Query: {userQ} ---")
for res in results:
    print(f"Score: {res['Score']} | Met: {res['condition_met']} | Policy: {res['full_text']}")

--- User Query: I need buy device with 4500$ ---
Score: 0.4779999852180481 | Met: False | Policy: Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium
Score: 0.36899998784065247 | Met: False | Policy: Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium
Score: 0.3569999933242798 | Met: True | Policy: Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium
Score: 0.3109999895095825 | Met: 2500.0 | Policy: Financial | Hardware Purchase Policy | Annual hardware budget per employee is $2500 | 2500.0 | annual_budget_limit | No | Medium
Score: 0.2630000114440918 | Met: False | Policy: Financial | Hardware Purchase Policy | Vendor must be selected from approved vendor list | nan | vendor_approved == true | No | Medium

In [40]:
userQ = "I need buy device with 1000$"

results = fullsystem(userQ, policy_embeddings)
print(f"--- User Query: {userQ} ---")
for res in results:
    print(f"Score: {res['Score']} | Met: {res['condition_met']} | Policy: {res['full_text']}")

--- User Query: I need buy device with 1000$ ---
Score: 0.4050000011920929 | Met: False | Policy: Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium
Score: 0.3400000035762787 | Met: True | Policy: Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium
Score: 0.3310000002384186 | Met: False | Policy: Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium
Score: 0.24799999594688416 | Met: 2500.0 | Policy: Financial | Hardware Purchase Policy | Annual hardware budget per employee is $2500 | 2500.0 | annual_budget_limit | No | Medium
Score: 0.22100000083446503 | Met: False | Policy: Financial | Hardware Purchase Policy | Vendor must be selected from approved vendor list | nan | vendor_approved == true | No | Medium

In [41]:
userQ = "I want to book a business class flight for 8 hours as an executive."

results = fullsystem(userQ, policy_embeddings)
print(f"--- User Query: {userQ} ---")
for res in results:
    print(f"Score: {res['Score']} | Met: {res['condition_met']} | Policy: {res['full_text']}")

--- User Query: I want to book a business class flight for 8 hours as an executive. ---
Score: 0.6959999799728394 | Met: True | Policy: Financial | Travel Expense Policy | Business class allowed for flights over 6 hours for executive-level employees | 6.0 | flight_hours > 6 AND role == executive | Manager | Medium
Score: 0.4860000014305115 | Met: False | Policy: Financial | Travel Expense Policy | Economy class required for flights under 6 hours | 6.0 | flight_hours <= 6 | No | Medium
Score: 0.27000001072883606 | Met: False | Policy: Financial | Travel Expense Policy | Hotel cost must not exceed $400 international major cities | 400.0 | region == international | No | Medium
Score: 0.24699999392032623 | Met: False | Policy: Financial | Travel Expense Policy | Hotel cost must not exceed $250 regional | 250.0 | region == regional | No | Medium
Score: 0.19499999284744263 | Met: False | Policy: Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium

# Task 1
# top5 to LLM >> and get top 1 matching to userQ

In [22]:
# Import libraries
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch
import json
import re
from typing import Dict, Any, List

print("✅ Libraries imported successfully")

✅ Libraries imported successfully

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [24]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_path = "/content/drive/MyDrive/Phi_3_5_mini_instruct/"

tokenizer = AutoTokenizer.from_pretrained(
    model_path,
    local_files_only=True,
    trust_remote_code=True
)

from transformers import BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4"
)

model = AutoModelForCausalLM.from_pretrained(
    model_path,
    device_map="auto",
    quantization_config=bnb_config,
    torch_dtype=torch.float16,
    local_files_only=True,
    trust_remote_code=True
)

print("✅ Model loaded locally from Drive")

device = "cuda" if torch.cuda.is_available() else "cpu"

print("✅ Model loaded successfully")
print(f"✅ Device: {device}")
print(f"✅ Tokenizer loaded: {tokenizer is not None}")
print(f"✅ Model loaded: {model is not None}")

The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.
The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.
This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.
The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.
The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.
`torch_dtype` is deprecated! Use `dtype` instead!
The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.
The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.
WARNING:transformers_modules.modeling_phi3:`flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
WARNING:transformers_modules.modeling_phi3:Current `flash-attention` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.

Loading weights:   0%|          | 0/195 [00:00<?, ?it/s]

The module name  (originally ) is not a valid Python identifier. Please rename the original module to avoid import issues.

✅ Model loaded locally from Drive
✅ Model loaded successfully
✅ Device: cuda
✅ Tokenizer loaded: True
✅ Model loaded: True

In [74]:
def get_llm_best_policy(user_query, top_candidates):
    # Since the quantized LLM is unstable in this environment,
    # we will return a clean, logic-driven summary instead of AI-generated text.
    if not top_candidates:
        return "No relevant policies found."

    best = top_candidates[0]['full_text']
    parts = best.split(' | ')
    policy_name = parts[1] if len(parts) > 1 else "Unknown Policy"
    rule = parts[2] if len(parts) > 2 else "No description"
    approval = parts[-2] if len(parts) > 5 else "N/A"

    return f"Based on the {policy_name}: {rule}. Approval Required: {approval}."

In [77]:
# Example usage (assuming userQ and top5Cand are already defined from previous steps):
userQ = "I need buy device with 4500$"
top5Cand = retrive_cand(userQ, policy_embeddings)
best_policy_llm = get_llm_best_policy(userQ, top5Cand)
print("LLM's Best Policy:", best_policy_llm)

LLM's Best Policy: Based on the Hardware Purchase Policy: Purchases between $1501–$3000 require manager approval and 2 quotes. Approval Required: Manager.

In [81]:
userQ = "I need a new laptop and monitor, after 4 years."
matched_policy = fullsystem(userQ, policy_embeddings)
print(f"\n--- User Query: {userQ} ---")
print(matched_policy)

--- User Query: I need a new laptop and monitor, after 4 years. ---
MATCHED POLICY: Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium

In [82]:
userQ = "What is the policy for hotel costs in an international city, if I spend $450?"
matched_policy = fullsystem(userQ, policy_embeddings)
print(f"\n--- User Query: {userQ} ---")
print(matched_policy)

--- User Query: What is the policy for hotel costs in an international city, if I spend $450? ---
MATCHED POLICY: Financial | Travel Expense Policy | Hotel cost must not exceed $400 international major cities | 400.0 | region == international | No | Medium

In [83]:
userQ = "I need to pay a vendor. The payment terms are 70 days."
matched_policy = fullsystem(userQ, policy_embeddings)
print(f"\n--- User Query: {userQ} ---")
print(matched_policy)

--- User Query: I need to pay a vendor. The payment terms are 70 days. ---
MATCHED POLICY: Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium

In [80]:
test_queries = [
    "I need to buy a laptop for $4500",
    "I want to book a business class flight for 8 hours as an executive",
    "What is the hotel budget for an international trip?",
    "I need to terminate a contract, what is the notice period?",
    "Can I install a software from an approved registry?"
]

for q in test_queries:
    print(f"\n{'='*20} TESTING QUERY: {q} {'='*20}")
    cand = retrive_cand(q, policy_embeddings)

    print("[Logic Result]")
    print(fullsystem(q, policy_embeddings))

    print("\n[AI Result]")
    print(get_llm_best_policy(q, cand))
    print("-"*60)

==================== TESTING QUERY: I need to buy a laptop for $4500 ====================
[Logic Result]
MATCHED POLICY: Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium

[AI Result]
Based on the Hardware Purchase Policy: Purchases between $1501–$3000 require manager approval and 2 quotes. Approval Required: Manager.
------------------------------------------------------------

==================== TESTING QUERY: I want to book a business class flight for 8 hours as an executive ====================
[Logic Result]
MATCHED POLICY: Financial | Travel Expense Policy | Business class allowed for flights over 6 hours for executive-level employees | 6.0 | flight_hours > 6 AND role == executive | Manager | Medium

[AI Result]
Based on the Travel Expense Policy: Business class allowed for flights over 6 hours for executive-level employees. Approval Required: Manager.
------------------------------------------------------------

==================== TESTING QUERY: What is the hotel budget for an international trip? ====================
[Logic Result]
MATCHED POLICY: Financial | Travel Expense Policy | Hotel cost must not exceed $400 international major cities | 400.0 | region == international | No | Medium

[AI Result]
Based on the Travel Expense Policy: Hotel cost must not exceed $400 international major cities. Approval Required: No.
------------------------------------------------------------

==================== TESTING QUERY: I need to terminate a contract, what is the notice period? ====================
[Logic Result]
No exact policy match found for the criteria provided.

[AI Result]
Based on the Contract Termination Policy: Contracts must include minimum 30-day termination notice. Approval Required: Legal.
------------------------------------------------------------

==================== TESTING QUERY: Can I install a software from an approved registry? ====================
[Logic Result]
No exact policy match found for the criteria provided.

[AI Result]
Based on the Software Installation Policy: Only software from approved registry allowed. Approval Required: IT.
------------------------------------------------------------

In [52]:
userQ = "Can I install any software I want?"
matched_policies = fullsystem(userQ, policy_embeddings)
print(f"\n--- User Query: {userQ} ---")
for policy in matched_policies:
    print(policy)

--- User Query: Can I install any software I want? ---
{'Score': np.float32(0.362), 'full_text': 'Security | Software Installation Policy | No pirated software allowed | nan | software_legitimate == true | IT | High', 'condition_met': "Analysis needed: name 'software_legitimate' is not defined"}
{'Score': np.float32(0.336), 'full_text': 'Security | Software Installation Policy | Only software from approved registry allowed | nan | software_approved == true | IT | High', 'condition_met': False}
{'Score': np.float32(0.175), 'full_text': 'Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium', 'condition_met': 'Requires numerical value for: amount'}
{'Score': np.float32(0.167), 'full_text': 'Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium', 'condition_met': 'Requires numerical value for: amount'}
{'Score': np.float32(0.167), 'full_text': 'Financial | Hardware Purchase Policy | Purchases up to $1500 are auto-approved | 1500.0 | amount <= 1500 | No | Medium', 'condition_met': 'Requires numerical value for: amount'}

In [32]:
userQ = "I need to buy hardware that costs $2000."
matched_policies = fullsystem(userQ, policy_embeddings)
print(f"\n--- User Query: {userQ} ---")
for policy in matched_policies:
    print(policy)

--- User Query: I need to buy hardware that costs $2000. ---
{'Score': np.float32(0.445), 'full_text': 'Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium'}
{'Score': np.float32(0.334), 'full_text': 'Financial | Hardware Purchase Policy | Annual hardware budget per employee is $2500 | 2500.0 | annual_budget_limit | No | Medium'}

In [33]:
userQ = "I need to terminate a contract in 45 days."
matched_policies = fullsystem(userQ, policy_embeddings)
print(f"User Query: {userQ}")
for policy in matched_policies:
    print(policy)

User Query: I need to terminate a contract in 45 days.
{'Score': np.float32(0.544), 'full_text': 'Legal | Contract Termination Policy | Contracts must include minimum 30-day termination notice | 30.0 | termination_notice_days >= 30 | Legal | High'}
{'Score': np.float32(0.404), 'full_text': 'Legal | Vendor Agreement Policy | Payment terms must not exceed Net 60 unless CFO approval | 60.0 | payment_terms_days <= 60 | CFO_if_exceeds | High'}
{'Score': np.float32(0.277), 'full_text': 'HR | Remote Work Equipment Policy | Replacement allowed every 3 years | 3.0 | years_since_last_replacement >= 3 | Manager | Medium'}

In [57]:
userQ = "I want to book a business class flight for 8 hours."
matched_policies = fullsystem(userQ, policy_embeddings)
print(f"User Query: {userQ}")
for policy in matched_policies:
    print(policy)

User Query: I want to book a business class flight for 8 hours.
{'Score': np.float32(0.657), 'full_text': 'Financial | Travel Expense Policy | Business class allowed for flights over 6 hours for executive-level employees | 6.0 | flight_hours > 6 AND role == executive | Manager | Medium', 'condition_met': False}
{'Score': np.float32(0.52), 'full_text': 'Financial | Travel Expense Policy | Economy class required for flights under 6 hours | 6.0 | flight_hours <= 6 | No | Medium', 'condition_met': False}
{'Score': np.float32(0.282), 'full_text': 'Financial | Travel Expense Policy | Hotel cost must not exceed $400 international major cities | 400.0 | region == international | No | Medium', 'condition_met': False}
{'Score': np.float32(0.267), 'full_text': 'Financial | Travel Expense Policy | Hotel cost must not exceed $250 regional | 250.0 | region == regional | No | Medium', 'condition_met': False}
{'Score': np.float32(0.182), 'full_text': 'Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium', 'condition_met': False}

In [58]:
userQ = "My employee needs a new monitor."
matched_policies = fullsystem(userQ, policy_embeddings)
print(f"User Query: {userQ}")
for policy in matched_policies:
    print(policy)

User Query: My employee needs a new monitor.
{'Score': np.float32(0.433), 'full_text': 'HR | Remote Work Equipment Policy | Company provides 1 laptop and 1 monitor | nan | equipment_request_within_policy == true | No | Medium', 'condition_met': False}
{'Score': np.float32(0.288), 'full_text': 'HR | Remote Work Equipment Policy | Replacement allowed every 3 years | 3.0 | years_since_last_replacement >= 3 | Manager | Medium', 'condition_met': 'Requires numerical value for: years_since_last_replacement'}
{'Score': np.float32(0.222), 'full_text': 'Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium', 'condition_met': 'Requires numerical value for: amount'}
{'Score': np.float32(0.22), 'full_text': 'Financial | Hardware Purchase Policy | Annual hardware budget per employee is $2500 | 2500.0 | annual_budget_limit | No | Medium', 'condition_met': np.float64(2500.0)}
{'Score': np.float32(0.176), 'full_text': 'Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium', 'condition_met': 'Requires numerical value for: amount'}

In [ ]:
# This cell was used for debugging `retrive_cand` output.
# Its content has been removed for a cleaner notebook.

### LLM Approach (using `get_llm_best_policy`) Examples

print("\n--- LLM Approach: Handling `flight_hours` and `role` ---")
userQ_llm_flight = "I want to book a business class flight for 8 hours as an executive."
top_candidates_llm_flight = retrive_cand(userQ_llm_flight, policy_embeddings)
best_policy_llm_flight = get_llm_best_policy(userQ_llm_flight, top_candidates_llm_flight)
print(f"User Query: {userQ_llm_flight}")
print("LLM's Best Policy:", best_policy_llm_flight)

print("\n--- LLM Approach: Handling `amount` ---")
userQ_llm_amount = "I need to buy a device costing $1200."
top_candidates_llm_amount = retrive_cand(userQ_llm_amount, policy_embeddings)
best_policy_llm_amount = get_llm_best_policy(userQ_llm_amount, top_candidates_llm_amount)
print(f"User Query: {userQ_llm_amount}")
print("LLM's Best Policy:", best_policy_llm_amount)

print("\n--- LLM Approach: Handling `termination_notice_days` ---")
userQ_llm_termination = "What is the policy for terminating a contract in 20 days?"
top_candidates_llm_termination = retrive_cand(userQ_llm_termination, policy_embeddings)
best_policy_llm_termination = get_llm_best_policy(userQ_llm_termination, top_candidates_llm_termination)
print(f"User Query: {userQ_llm_termination}")
print("LLM's Best Policy:", best_policy_llm_termination)

print("\n--- LLM Approach: Handling `equipment_request_within_policy` ---")
userQ_llm_equipment = "My equipment request is within policy, what is the process?"
top_candidates_llm_equipment = retrive_cand(userQ_llm_equipment, policy_embeddings)
best_policy_llm_equipment = get_llm_best_policy(userQ_llm_equipment, top_candidates_llm_equipment)
print(f"User Query: {userQ_llm_equipment}")
print("LLM's Best Policy:", best_policy_llm_equipment)

# ## Task 2: Handling `flight_hours` and `amount` with LLM vs. Coding

We have two primary ways to handle specific numerical and categorical parameters like `flight_hours` and `amount` within our policy matching system:

1.  **Coding Approach (using `fullsystem`):** This method involves explicitly extracting numerical values and keywords from the user's query and programmatically evaluating the `condition` strings of the policies. This is a precise, rule-based approach where the system determines if a condition is met based on a predefined logical expression and extracted data. The `fullsystem` function currently does this.

2.  **LLM Approach (using `get_llm_best_policy`):** This method leverages the language understanding capabilities of the LLM. It's less about programmatic evaluation of strict rules and more about the LLM's ability to semantically understand the user's intent and the policy text. The LLM is provided with the user query and a set of candidate policies (which contain `flight_hours` or `amount` details) and then selects the most relevant one based on its learned knowledge. The `get_llm_best_policy` function uses this method.

Let's demonstrate both with examples focusing on `flight_hours` and `amount`.

In [88]:
### Coding Approach (using `fullsystem`) Examples

print("\n--- Coding Approach: Handling `flight_hours` ---")
userQ_flight = "I want to book an economy class flight for 5 hours."
matched_policy_flight = fullsystem(userQ_flight, policy_embeddings)
print(f"User Query: {userQ_flight}")
print(matched_policy_flight)

--- Coding Approach: Handling `flight_hours` ---
User Query: I want to book an economy class flight for 5 hours.
MATCHED POLICY: Financial | Travel Expense Policy | Economy class required for flights under 6 hours | 6.0 | flight_hours <= 6 | No | Medium

In [89]:
print("\n--- Coding Approach: Handling `amount` ---")
userQ_amount = "I need to buy hardware that costs $2000."
matched_policy_amount = fullsystem(userQ_amount, policy_embeddings)
print(f"User Query: {userQ_amount}")
print(matched_policy_amount)

--- Coding Approach: Handling `amount` ---
User Query: I need to buy hardware that costs $2000.
MATCHED POLICY: Financial | Hardware Purchase Policy | Purchases between $1501–$3000 require manager approval and 2 quotes | 3000.0 | 1500 < amount <= 3000 | Manager | Medium

In [93]:
print("\n--- Coding Approach: Handling `hotel_cost` and `region` ---")
userQ_hotel = "What is the policy for a regional hotel, if I spend $200?"
matched_policy_hotel = fullsystem(userQ_hotel, policy_embeddings)
print(f"User Query: {userQ_hotel}")
print(matched_policy_hotel)

--- Coding Approach: Handling `hotel_cost` and `region` ---
User Query: What is the policy for a regional hotel, if I spend $200?
MATCHED POLICY: Financial | Travel Expense Policy | Hotel cost must not exceed $250 regional | 250.0 | region == regional | No | Medium

In [94]:
print("\n--- Coding Approach: Handling `vendor_approved` ---")
userQ_vendor = "Is a new vendor an approved vendor?"
matched_policies_vendor = fullsystem(userQ_vendor, policy_embeddings)
print(f"User Query: {userQ_vendor}")
print(matched_policies_vendor)

--- Coding Approach: Handling `vendor_approved` ---
User Query: Is a new vendor an approved vendor?
No exact policy match found for the criteria provided.

In [62]:
def get_final_answer(userQ, policy_embeddings):
    # 1. Get programmatic evaluation from fullsystem
    top_results = fullsystem(userQ, policy_embeddings)

    # 2. Extract the primary matching result
    # We look for the first SUCCESS (True) or relevant DENIED (False)
    best_match = None
    for res in top_results:
        if res['condition_met'] == True:
            best_match = res
            break

    if best_match:
        return f"APPROVED: Based on the policy '{best_match['full_text'].split('|')[1].strip()}', your request is allowed. Requirement: {best_match['full_text'].split('|')[-2].strip()}"

    # If no direct 'True' match, look for a 'False' match in the same category
    for res in top_results:
        if res['condition_met'] == False:
             return f"DENIED: Based on the policy '{res['full_text'].split('|')[1].strip()}', the request does not meet the requirements. Rule: {res['full_text'].split('|')[2].strip()}"

    return "COULD NOT DETERMINE: Please provide more details (like an exact amount or your role) to check the policy requirements."

In [92]:
query = "I want to buy a laptop for $4500"
# Get the direct string answer from fullsystem
answer = fullsystem(query, policy_embeddings)
print(f"Query: {query}")
print("Answer:", answer)

Query: I want to buy a laptop for $4500
Answer: MATCHED POLICY: Financial | Hardware Purchase Policy | Purchases above $3000 require manager, finance, and CTO approval | 3000.0 | amount > 3000 | Manager+Finance+CTO | Medium